/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author user
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        LabelTCabello = new javax.swing.JLabel();
        ButtonHeadIzq = new javax.swing.JButton();
        LabelChHead = new javax.swing.JLabel();
        ButtonHeadDer = new javax.swing.JButton();
        LabelTBody = new javax.swing.JLabel();
        ButtonBodyIzq = new javax.swing.JButton();
        LabelChBody = new javax.swing.JLabel();
        ButtonBodyDer = new javax.swing.JButton();
        PanelFBase = new javax.swing.JPanel();
        PanelFHead = new javax.swing.JPanel();
        PanelFBody = new javax.swing.JPanel();
        LabelTitulo1 = new javax.swing.JLabel();
        ButtonDownload = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funko Design");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(255, 204, 153));

        LabelTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        LabelTitulo.setText("Funko");
        LabelTitulo.setToolTipText("");

        LabelTCabello.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        LabelTCabello.setText("Cabeza");
        LabelTCabello.setToolTipText("");

        ButtonHeadIzq.setText("<--");
        ButtonHeadIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHeadIzqActionPerformed(evt);
            }
        });

        LabelChHead.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        LabelChHead.setText("...");
        LabelChHead.setToolTipText("");
        LabelChHead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ButtonHeadDer.setText("-->");
        ButtonHeadDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHeadDerActionPerformed(evt);
            }
        });

        LabelTBody.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        LabelTBody.setText("Cuerpo");
        LabelTBody.setToolTipText("");

        ButtonBodyIzq.setText("<--");
        ButtonBodyIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBodyIzqActionPerformed(evt);
            }
        });

        LabelChBody.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        LabelChBody.setText("...");
        LabelChBody.setToolTipText("");
        LabelChBody.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ButtonBodyDer.setText("-->");
        ButtonBodyDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBodyDerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFHeadLayout = new javax.swing.GroupLayout(PanelFHead);
        PanelFHead.setLayout(PanelFHeadLayout);
        PanelFHeadLayout.setHorizontalGroup(
            PanelFHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        PanelFHeadLayout.setVerticalGroup(
            PanelFHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelFBodyLayout = new javax.swing.GroupLayout(PanelFBody);
        PanelFBody.setLayout(PanelFBodyLayout);
        PanelFBodyLayout.setHorizontalGroup(
            PanelFBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelFBodyLayout.setVerticalGroup(
            PanelFBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelFBaseLayout = new javax.swing.GroupLayout(PanelFBase);
        PanelFBase.setLayout(PanelFBaseLayout);
        PanelFBaseLayout.setHorizontalGroup(
            PanelFBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelFHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelFBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelFBaseLayout.setVerticalGroup(
            PanelFBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFBaseLayout.createSequentialGroup()
                .addComponent(PanelFHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelFBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LabelTitulo1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        LabelTitulo1.setText("Personalización de");
        LabelTitulo1.setToolTipText("");

        ButtonDownload.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        ButtonDownload.setText("DESCARGAR");
        ButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelTCabello)
                            .addComponent(LabelTBody))
                        .addGap(47, 47, 47)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTitulo)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonBodyIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonHeadIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelChHead, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelChBody, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonHeadDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonBodyDer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(LabelTitulo1)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(ButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))))))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(LabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTCabello, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelChHead, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonHeadIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonHeadDer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelChBody, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTBody, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBodyIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBodyDer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(ButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonHeadIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHeadIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHeadIzqActionPerformed

    private void ButtonHeadDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHeadDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHeadDerActionPerformed

    private void ButtonBodyIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBodyIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBodyIzqActionPerformed

    private void ButtonBodyDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBodyDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBodyDerActionPerformed

    private void ButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDownloadActionPerformed
        /**try {
            // Obtener las imágenes directamente de los JPanel
            BufferedImage headBufferedImage = new BufferedImage(PanelFHead.getWidth(), PanelFHead.getHeight(), BufferedImage.TYPE_INT_ARGB);
            PanelFHead.paint(headBufferedImage.getGraphics());

            BufferedImage bodyBufferedImage = new BufferedImage(PanelFBody.getWidth(), PanelFBody.getHeight(), BufferedImage.TYPE_INT_ARGB);
            PanelFBody.paint(bodyBufferedImage.getGraphics());

            BufferedImage baseBufferedImage = new BufferedImage(PanelFBase.getWidth(), PanelFBase.getHeight(), BufferedImage.TYPE_INT_ARGB);
            PanelFBody.paint(baseBufferedImage.getGraphics());

            // Combinar las imágenes
            BufferedImage combinedImage = new BufferedImage(baseBufferedImage.getWidth(), baseBufferedImage.getHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = combinedImage.createGraphics();
            g.drawImage(bodyBufferedImage, 0, 190, null);
            g.drawImage(headBufferedImage, 0, 0, null);
            g.dispose();

            // Guardar la imagen combinada
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar imagen combinada");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG Images", "png");
            fileChooser.setFileFilter(filter);
            System.out.println(this);
            int userSelection = fileChooser.showSaveDialog(this);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                ImageIO.write(combinedImage, "png", fileToSave);
                JOptionPane.showMessageDialog(this, "Imagen guardada exitosamente!");
            }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al guardar la imagen.");
    }**/
    }//GEN-LAST:event_ButtonDownloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonBodyDer;
    public javax.swing.JButton ButtonBodyIzq;
    public javax.swing.JButton ButtonDownload;
    public javax.swing.JButton ButtonHeadDer;
    public javax.swing.JButton ButtonHeadIzq;
    public javax.swing.JLabel LabelChBody;
    public javax.swing.JLabel LabelChHead;
    private javax.swing.JLabel LabelTBody;
    private javax.swing.JLabel LabelTCabello;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTitulo1;
    public javax.swing.JPanel PanelFBase;
    public javax.swing.JPanel PanelFBody;
    public javax.swing.JPanel PanelFHead;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
